#ifndef LEVICULUM_H
#define LEVICULUM_H

/* Generated with cbindgen:0.27.0 */

/* Warning: this file is autogenerated by cbindgen. Do not modify manually. */

#include <stdarg.h>
#include <stdbool.h>
#include <stdint.h>
#include <stdlib.h>

#define LNS_OK 0

#define LNS_ERR_NULL_PTR -1

#define LNS_ERR_INVALID_ARG -2

#define LNS_ERR_INIT_FAILED -3

#define LNS_ERR_NOT_RUNNING -4

#define LNS_ERR_ALREADY_RUNNING -5

#define LNS_ERR_IO -6

#define LNS_ERR_CRYPTO -7

#define LNS_ERR_BUFFER_TOO_SMALL -8

/**
 * Opaque handle to an Identity
 */
typedef struct LnsIdentity LnsIdentity;

/**
 * Get the error message for an error code
 */
 const char *lns_error_string(int code) ;

/**
 * Decrypt data encrypted for this identity
 *
 * Requires the identity to have private keys.
 *
 * Returns the plaintext length, or negative error code.
 */
 int lns_identity_decrypt(const struct LnsIdentity *identity, const uint8_t *ciphertext, uintptr_t ciphertext_len, uint8_t *out_plaintext, uintptr_t *out_len) ;

/**
 * Encrypt data for an identity
 *
 * The ciphertext can only be decrypted by the holder of the identity's private key.
 * Output format: [ephemeral_pub (32)] [token (variable)]
 *
 * Returns the ciphertext length, or negative error code.
 */
 int lns_identity_encrypt(const struct LnsIdentity *identity, const uint8_t *plaintext, uintptr_t plaintext_len, uint8_t *out_ciphertext, uintptr_t *out_len) ;

/**
 * Free an identity
 */
 void lns_identity_free(struct LnsIdentity *identity) ;

/**
 * Load identity from private key bytes (64 bytes)
 */
 struct LnsIdentity *lns_identity_from_private_key(const uint8_t *key, uintptr_t key_len) ;

/**
 * Load identity from public key bytes (64 bytes)
 */
 struct LnsIdentity *lns_identity_from_public_key(const uint8_t *key, uintptr_t key_len) ;

/**
 * Check if identity has private keys
 *
 * Returns 1 if identity has private keys, 0 otherwise.
 */
 int lns_identity_has_private_keys(const struct LnsIdentity *identity) ;

/**
 * Get the identity hash (16 bytes)
 */
 int lns_identity_hash(const struct LnsIdentity *identity, uint8_t *out_hash, uintptr_t *out_len) ;

/**
 * Create a new random identity
 */
 struct LnsIdentity *lns_identity_new(void) ;

/**
 * Get the private key bytes (64 bytes)
 *
 * Returns LNS_ERR_CRYPTO if identity has no private keys (public-only).
 */
 int lns_identity_private_key(const struct LnsIdentity *identity, uint8_t *out_key, uintptr_t *out_len) ;

/**
 * Get the public key bytes (64 bytes)
 */
 int lns_identity_public_key(const struct LnsIdentity *identity, uint8_t *out_key, uintptr_t *out_len) ;

/**
 * Sign a message
 */
 int lns_identity_sign(const struct LnsIdentity *identity, const uint8_t *message, uintptr_t message_len, uint8_t *out_signature, uintptr_t *out_len) ;

/**
 * Verify a signature
 */
 int lns_identity_verify(const struct LnsIdentity *identity, const uint8_t *message, uintptr_t message_len, const uint8_t *signature, uintptr_t signature_len) ;

/**
 * Initialize the library (call once at startup)
 */
 int lns_init(void) ;

/**
 * Free a string allocated by the library
 */
 void lns_string_free(char *s) ;

/**
 * Get the library version string
 */
 const char *lns_version(void) ;

#endif  /* LEVICULUM_H */
