//! The receiver half: what our `lncp -l -a` does with an advertisement from a
//! sender whose identify was lost.
//!
//! `lncp_identify_loss_interop_tests` measured our SENDER against a Python
//! listener that answers the same loss in 2.3 s. This file measures our
//! LISTENER, and before the fix it was the worse end of the pair: `lncp -l -a`
//! armed `AcceptAll` only from the `LinkIdentified` event, so until an identify
//! arrived the link kept `AcceptNone`, and `handle_resource_advertisement`
//! discarded the advertisement with no event and no packet
//! (`leviculum-core/src/node/link_management.rs:2542-2544`). The sender heard
//! nothing at all and had to wait out its own advertisement retries.
//!
//! Python's `rncp` does not have that state. `client_link_established`
//! (`reference/Reticulum/RNS/Utilities/rncp.py:238-241`) arms `ACCEPT_APP` on
//! every incoming link, and `receive_resource_callback` (`rncp.py:254-266`)
//! decides per advertisement: no remote identity and no `-n` means False,
//! which `Link.py:1091-1097` turns into `RNS.Resource.reject` — one RCL, one
//! RTT after the advertisement. `AcceptNone` is the strategy for a link that
//! takes no resources; it was never the right answer for a link that has not
//! decided yet.
//!
//! Both tests here drive the real `leviculum_cli::cp::run_listen`, the loop the
//! `lncp` binary runs, through [`crate::identify_loss_proxy`] — the same
//! frame-aware proxy, with our listener as the upstream this time, so the
//! swallowed LINKIDENTIFY is the one travelling towards us.

use std::path::PathBuf;
use std::sync::atomic::{AtomicU32, Ordering};
use std::sync::{Arc, Mutex};
use std::time::{Duration, Instant};

use leviculum_core::{Destination, DestinationHash, DestinationType, Direction, Identity};
use leviculum_std::driver::{ReticulumNode, ReticulumNodeBuilder};
use rand_core::OsRng;

use crate::harness::find_available_ports;
use crate::identify_loss_proxy::{
    prepare_rncp_sender, python_rns_available, spawn_identify_dropping_proxy, spawn_rncp_sender,
    ProxyLog, CTX_RESOURCE_ADV, CTX_RESOURCE_RCL,
};

static TEST_COUNTER: AtomicU32 = AtomicU32::new(0);

/// How long the rejection may take after the advertisement before it stops
/// being an answer and starts being a timeout. One loopback RTT is under a
/// millisecond; this is three orders of magnitude of headroom for a loaded
/// gate machine, and still far below the first advertisement retry of either
/// stack.
const RCL_WITHIN: Duration = Duration::from_secs(2);

/// Our `lncp -l` running in-process: the destination hash a sender needs, the
/// directory it saves into, and the task running the real serve loop.
struct LncpListener {
    dest_hash: DestinationHash,
    save_dir: PathBuf,
    task: tokio::task::JoinHandle<()>,
    node: Arc<ReticulumNode>,
}

impl Drop for LncpListener {
    fn drop(&mut self) {
        self.task.abort();
    }
}

/// Boot `lncp -l -a <allowed_hash> -s <dir>` on a TCP server interface,
/// announcing every 5 s.
///
/// The identity is generated by the caller so a sender's allow-list and this
/// listener's `-a` can be written before anything starts, exactly as the
/// Python-listener direction does it.
async fn spawn_lncp_listener(
    tcp_port: u16,
    identity: &Identity,
    allowed: Vec<[u8; 16]>,
    tmp: &std::path::Path,
) -> LncpListener {
    let save_dir = tmp.join("lncp-received");
    std::fs::create_dir_all(&save_dir).expect("create lncp save dir");
    let storage = tmp.join("listener-storage");
    std::fs::create_dir_all(&storage).expect("create listener storage");

    // The hash run_listen will register (cp.rs:369-378), computed here so the
    // sender can be pointed at it before the loop starts.
    let dest_hash = *Destination::new(
        Some(identity.clone()),
        Direction::In,
        DestinationType::Single,
        "rncp",
        &["receive"],
    )
    .expect("build listener destination")
    .hash();

    let listen_addr: std::net::SocketAddr = format!("127.0.0.1:{tcp_port}")
        .parse()
        .expect("listener addr");
    let mut node = ReticulumNodeBuilder::new()
        .enable_transport(false)
        .add_tcp_server(listen_addr)
        .storage_path(storage)
        .build()
        .await
        .expect("build listener node");
    let mut events = node.take_event_receiver().expect("event receiver");
    node.start().await.expect("start listener node");
    let node = Arc::new(node);

    let task = tokio::spawn({
        let node = Arc::clone(&node);
        let identity = identity.clone();
        let save_dir = save_dir.clone();
        async move {
            let _ = leviculum_cli::cp::run_listen(
                &node,
                &mut events,
                identity,
                Some(save_dir),
                true,
                false,
                &allowed,
                5,
                1,
                false,
                false,
                None,
                false,
            )
            .await;
        }
    });

    LncpListener {
        dest_hash,
        save_dir,
        task,
        node,
    }
}

/// A Python `rncp -S` pushes 1 KiB to our `lncp -l -a <its hash>` through the
/// proxy, which swallows the LINKIDENTIFY on the way in.
///
/// Our listener therefore sees an advertisement from a link it cannot place.
/// What it does about that is the whole test: before the fix, nothing at all
/// (five advertisements went upstream and not one packet came back, and rncp
/// gave up 5.7 s later on its own retry ladder — 36 s at the 1.3 s RTT of the
/// LoRa PHY the hardware cell runs on). After it, an RCL inside one RTT of
/// each advertisement.
///
/// The test watches the wire rather than waiting for the sender, because this
/// sender cannot conclude: `Resource.REJECTED` and `Resource.NONE` are both
/// `0x00` in RNS 1.5.2 (`reference/Reticulum/RNS/Resource.py:142-152`), so
/// rncp's `while resource.status < RNS.Resource.TRANSFERRING` spin
/// (`rncp.py:703-708`) never sees the rejection it was told about. That is the
/// reference's own dead end on a rejection every Python listener can send; our
/// sender, which reports it and retries once, is measured in
/// `lncp_identify_loss_interop_tests`.
#[tokio::test]
async fn lncp_listener_rejects_an_advertisement_whose_identify_was_lost() {
    if !python_rns_available() {
        eprintln!(
            "skipping lncp listener identify-loss interop: python3 + vendored RNS unavailable"
        );
        return;
    }
    crate::common::init_tracing();

    let test_id = TEST_COUNTER.fetch_add(1, Ordering::Relaxed);
    let tmp = crate::common::temp_storage("lncp_listener_identify_loss", &format!("run{test_id}"));

    let sender_identity = Identity::generate(&mut OsRng);
    let listener_identity = Identity::generate(&mut OsRng);

    let (ports, _alloc) = find_available_ports::<2>().await.expect("allocate ports");
    let (listener_port, proxy_port) = (ports[0], ports[1]);

    let log = Arc::new(Mutex::new(ProxyLog::default()));
    spawn_identify_dropping_proxy(proxy_port, listener_port, 1, Arc::clone(&log)).await;

    let listener = spawn_lncp_listener(
        listener_port,
        &listener_identity,
        vec![*sender_identity.hash()],
        tmp.path(),
    )
    .await;
    let dest_hash_hex = hex::encode(listener.dest_hash.as_bytes());

    let (sender_config_dir, sender_identity_path) =
        prepare_rncp_sender(tmp.path(), &sender_identity, proxy_port);

    let payload: Vec<u8> = (0..1024u32).map(|i| (i % 251) as u8).collect();
    let file_path = tmp.path().join("identify-loss.bin");
    std::fs::write(&file_path, &payload).expect("write payload");

    // Our listener announces every 5 s (cp.rs:415-421); rncp's own path wait
    // (rncp.py:658-664) covers the gap.
    let mut sender = spawn_rncp_sender(
        &sender_config_dir,
        &sender_identity_path,
        &file_path,
        &dest_hash_hex,
        90,
    );

    let deadline = Instant::now() + Duration::from_secs(60);
    loop {
        let (saw_adv, saw_rcl) = {
            let log = log.lock().expect("proxy log");
            (
                log.saw_to_upstream(CTX_RESOURCE_ADV),
                log.saw_to_downstream(CTX_RESOURCE_RCL),
            )
        };
        if saw_rcl {
            break;
        }
        assert!(
            Instant::now() < deadline,
            "our listener never answered the advertisement. advertisement \
             seen={saw_adv}. {}\nrncp sender: {}",
            log.lock().expect("proxy log").evidence(),
            sender.log_tail(1500),
        );
        tokio::time::sleep(Duration::from_millis(50)).await;
    }

    // Long enough for more than two of the sender's advertisement retries: the
    // pre-fix arm fitted five of them into 5.7 s on this link. Nothing more
    // should be advertised now, because the answer already arrived.
    tokio::time::sleep(Duration::from_secs(3)).await;

    let (evidence, drops, adv_count, rcl_count, adv_to_rcl) = {
        let log = log.lock().expect("proxy log");
        (
            log.evidence(),
            log.dropped_identify,
            log.count_to_upstream(CTX_RESOURCE_ADV),
            log.count_to_downstream(CTX_RESOURCE_RCL),
            log.adv_to_rcl(),
        )
    };
    let sender_exit = sender.exited();
    let evidence = format!("{evidence} rncp exit={sender_exit:?}");

    assert_eq!(
        drops, 1,
        "the modelled loss must have fired exactly once. {evidence}"
    );
    let gap = adv_to_rcl.expect("the loop above only exits once an RCL was seen");
    assert!(
        gap < RCL_WITHIN,
        "the rejection must come back within one RTT of the advertisement, not \
         after the sender's retries; measured {gap:?}. {evidence}"
    );
    assert_eq!(
        rcl_count, adv_count,
        "every advertisement gets an answer, not just the first. {evidence}"
    );
    assert!(
        adv_count <= 2,
        "the sender must not run its retry ladder out: it needed five \
         advertisements before the fix. Two are possible without any fault of \
         ours, because `__advertise_job` sends the advertisement before \
         `register_outgoing_resource` (Resource.py:526-534), so a rejection \
         that arrives inside that window finds no resource to reject. \
         {evidence}"
    );
    assert!(
        sender_exit.is_none_or(|status| !status.success()),
        "rncp must not report success. {evidence}\nrncp sender: {}",
        sender.log_tail(1500),
    );
    assert!(
        !listener.save_dir.join("identify-loss.bin").is_file(),
        "an unidentified sender must not get its file stored. {evidence}"
    );
    assert!(
        listener.node.is_running(),
        "the listener must survive the rejection and stay up for the next \
         sender. {evidence}"
    );
}

/// The round trip: our sender against our listener, with the same frame gone.
///
/// This is the host form of the hardware cell `lora_lncp_auth_identify_loss`.
/// It needs both halves — the listener's rejection (this file) and the sender's
/// single re-identify (`lncp_identify_loss_interop_tests`, commit 273c259b) —
/// and neither alone delivers the file: without the rejection the sender waits
/// out its retries with nothing to react to, and without the retry the
/// rejection just ends the transfer sooner.
#[tokio::test]
async fn our_sender_and_our_listener_recover_from_a_lost_identify() {
    crate::common::init_tracing();

    let test_id = TEST_COUNTER.fetch_add(1, Ordering::Relaxed);
    let tmp = crate::common::temp_storage("lncp_roundtrip_identify_loss", &format!("run{test_id}"));

    let sender_identity = Identity::generate(&mut OsRng);
    let listener_identity = Identity::generate(&mut OsRng);

    let (ports, _alloc) = find_available_ports::<2>().await.expect("allocate ports");
    let (listener_port, proxy_port) = (ports[0], ports[1]);

    let log = Arc::new(Mutex::new(ProxyLog::default()));
    spawn_identify_dropping_proxy(proxy_port, listener_port, 1, Arc::clone(&log)).await;

    let listener = spawn_lncp_listener(
        listener_port,
        &listener_identity,
        vec![*sender_identity.hash()],
        tmp.path(),
    )
    .await;
    let dest_hash_hex = hex::encode(listener.dest_hash.as_bytes());

    let proxy_addr: std::net::SocketAddr = format!("127.0.0.1:{proxy_port}")
        .parse()
        .expect("proxy addr");
    let sender_storage = tmp.path().join("sender-storage");
    std::fs::create_dir_all(&sender_storage).expect("create sender storage");
    let mut sender = ReticulumNodeBuilder::new()
        .enable_transport(false)
        .add_tcp_client(proxy_addr)
        .storage_path(sender_storage)
        .build()
        .await
        .expect("build sender node");
    let mut sender_events = sender.take_event_receiver().expect("event receiver");
    sender.start().await.expect("start sender node");

    // The listener announces every 5 s (cp.rs:404-415) and there is no
    // transport node to answer a path request, so the announce is the only
    // readiness signal.
    let deadline = Instant::now() + Duration::from_secs(60);
    while !sender.has_path(&listener.dest_hash) {
        assert!(
            Instant::now() < deadline,
            "no announce from our listener within 60 s"
        );
        tokio::time::sleep(Duration::from_millis(200)).await;
    }

    let payload: Vec<u8> = (0..1024u32).map(|i| (i % 251) as u8).collect();
    let file_path = tmp.path().join("identify-loss.bin");
    std::fs::write(&file_path, &payload).expect("write payload");

    let result = leviculum_cli::cp::run_send(
        &sender,
        &mut sender_events,
        file_path.to_str().expect("utf-8 path"),
        &dest_hash_hex,
        Some(90.0),
        0,
        false,
        true,
        Some(&sender_identity),
        false,
    )
    .await
    .map_err(|e| e.to_string());

    let (evidence, drops, adv_count, saw_rcl) = {
        let log = log.lock().expect("proxy log");
        (
            log.evidence(),
            log.dropped_identify,
            log.count_to_upstream(CTX_RESOURCE_ADV),
            log.saw_to_downstream(CTX_RESOURCE_RCL),
        )
    };

    assert!(
        result.is_ok(),
        "our sender must deliver to our listener after one lost identify, got \
         {:?}. {evidence}",
        result.as_ref().err(),
    );
    assert_eq!(
        drops, 1,
        "the modelled loss must have fired exactly once. {evidence}"
    );
    assert!(
        saw_rcl,
        "the recovery runs through the listener's rejection, so an RCL must have \
         come back. {evidence}"
    );
    assert_eq!(
        adv_count, 2,
        "one rejected advertisement and one accepted, and no third. {evidence}"
    );

    let received = listener.save_dir.join("identify-loss.bin");
    let deadline = Instant::now() + Duration::from_secs(20);
    while !received.is_file() {
        assert!(
            Instant::now() < deadline,
            "our listener never wrote the file. {evidence}"
        );
        tokio::time::sleep(Duration::from_millis(200)).await;
    }
    assert_eq!(
        std::fs::read(&received).expect("read received file"),
        payload,
        "the listener must reassemble the payload byte for byte. {evidence}"
    );
}
