//! The propagation-node role against byte-exact fixtures from the Python
//! reference (Codeberg #384 part 1).
//!
//! Every hex string here comes from
//! `docs/src/appendix/lxmf/vectors/vectors.json`, generated by running the
//! vendored reference once (`gen_vectors.py`, `gen_propagation_node_vectors`):
//! the upload envelope and stamp verdicts are the genuine `LXStamper`'s, and
//! the `/get` responses are the genuine `LXMRouter.message_get_request`
//! handler's own bytes over a seeded two-message store. Our role must produce
//! the same bytes from the same inputs.

mod common;

use leviculum_core::resource::ResourceSource as _;
use leviculum_lxmf::{
    constants::{DESTINATION_LENGTH, STAMP_SIZE, WORKBLOCK_EXPAND_ROUNDS_PN},
    CooperativeStamper, GetOutcome, MemoryPropagationStore, MessageGetRequest, PropagationNode,
    PropagationNodeConfig, PropagationStore as _, TransferLimit, TransientId, UploadOutcome,
};

fn hex_bytes(id: &str, field: &str) -> Vec<u8> {
    hex::decode(common::fixture(id, field)).expect("fixture hex")
}

fn fixture_id(id: &str, field: &str) -> TransientId {
    hex_bytes(id, field).try_into().expect("32-byte id")
}

fn destination() -> [u8; DESTINATION_LENGTH] {
    hex_bytes("VEC-PN-UPLOAD", "destination_hex")
        .try_into()
        .expect("16-byte destination")
}

/// Stamp validation exactly as the host wires it: the streaming validator
/// over the reference's 1000-round PN workblock (`WORKBLOCK_EXPAND_ROUNDS_PN`,
/// `reference/LXMF/LXMF/LXStamper.py:13`).
fn validate(transient_id: &TransientId, stamp: &[u8; STAMP_SIZE], cost: u8) -> Option<u16> {
    let mut stamper = CooperativeStamper::cooperative(rand_core::OsRng);
    futures::executor::block_on(stamper.validate_stamp(
        transient_id,
        stamp,
        cost,
        WORKBLOCK_EXPAND_ROUNDS_PN,
    ))
    .expect("validation runs")
}

/// The small message the `/get` fixture store holds next to the uploaded
/// one, rebuilt by the generator's rule: `destination || bytes(0..100)`
/// with the stamp `bytes(0x40..0x60)` appended.
fn small_stamped() -> Vec<u8> {
    let mut body = destination().to_vec();
    body.extend((0u8..100).collect::<Vec<u8>>());
    body.extend(0x40u8..0x60);
    body
}

const FIXED_TIMESTAMP: u64 = 1_700_000_000;

/// The role with the fixture's two-message store seeded, matching the
/// generator's `propagation_entries`. Returns the node plus the small and
/// big transient IDs; that the reconstruction really is the generator's
/// store is proven by the byte-exact list-response assertion, whose bytes
/// embed both IDs in order.
fn seeded_node() -> (
    PropagationNode<MemoryPropagationStore>,
    TransientId,
    TransientId,
) {
    let mut node = PropagationNode::new(
        MemoryPropagationStore::new(64 * 1024),
        PropagationNodeConfig::default(),
    );
    let big_tid = fixture_id("VEC-PN-UPLOAD", "transient_id_hex");
    let mut big = hex_bytes("VEC-PN-UPLOAD", "lxmf_data_hex");
    big.extend(hex_bytes("VEC-PN-UPLOAD", "stamp_hex"));
    let small = small_stamped();
    let small_tid: TransientId =
        leviculum_core::crypto::full_hash(&small[..small.len() - STAMP_SIZE]);

    node.store_mut()
        .append(&small_tid, FIXED_TIMESTAMP, 0, &small)
        .expect("seed small");
    node.store_mut()
        .append(&big_tid, FIXED_TIMESTAMP, 8, &big)
        .expect("seed big");
    (node, small_tid, big_tid)
}

#[test]
fn the_reference_upload_envelope_is_accepted_and_stored_byte_exactly() {
    let mut node = PropagationNode::new(
        MemoryPropagationStore::new(64 * 1024),
        PropagationNodeConfig {
            stamp_cost: common::fixture("VEC-PN-UPLOAD", "stamp_cost")
                .parse()
                .expect("cost"),
            stamp_cost_flexibility: 0,
            ..PropagationNodeConfig::default()
        },
    );
    let envelope = hex_bytes("VEC-PN-UPLOAD", "envelope_hex");
    let expected_tid = fixture_id("VEC-PN-UPLOAD", "transient_id_hex");
    let expected_value: u16 = common::fixture("VEC-PN-UPLOAD", "stamp_value")
        .parse()
        .expect("value");

    let outcome = node.handle_upload(&envelope, FIXED_TIMESTAMP, |transient_id, stamp| {
        assert_eq!(
            transient_id, &expected_tid,
            "validation sees the fixture id"
        );
        validate(transient_id, stamp, 8)
    });
    match outcome {
        UploadOutcome::Accepted {
            transient_id,
            destination_hash,
            stamp_value,
            duplicate,
            ..
        } => {
            assert_eq!(transient_id, expected_tid);
            assert_eq!(destination_hash, destination());
            assert_eq!(stamp_value as u16, expected_value);
            assert!(!duplicate);
        }
        other => panic!("fixture upload must be accepted: {other:?}"),
    }

    // The stored body is `lxmf_data || stamp` exactly as the reference
    // writes it (LXMRouter.py:2512-2515).
    let mut expected_body = hex_bytes("VEC-PN-UPLOAD", "lxmf_data_hex");
    expected_body.extend(hex_bytes("VEC-PN-UPLOAD", "stamp_hex"));
    assert_eq!(
        node.store().read_body(&expected_tid).unwrap(),
        Some(expected_body)
    );
}

#[test]
fn our_validator_agrees_with_the_reference_validator_on_the_fixture_stamp() {
    let transient_id = fixture_id("VEC-PN-UPLOAD", "transient_id_hex");
    let stamp: [u8; STAMP_SIZE] = hex_bytes("VEC-PN-UPLOAD", "stamp_hex")
        .try_into()
        .expect("stamp");
    let value: u16 = common::fixture("VEC-PN-UPLOAD", "stamp_value")
        .parse()
        .expect("value");

    // Accepted at the announced cost with the reference's value
    // (fixture fields validator_accepts_at_cost / stamp_value)…
    assert_eq!(validate(&transient_id, &stamp, 8), Some(value));
    // …and rejected one bit above it (validator_rejects_above_value).
    assert_eq!(validate(&transient_id, &stamp, value as u8 + 1), None);
}

#[test]
fn a_failing_stamp_is_answered_with_the_reference_reject_packet() {
    let mut node = PropagationNode::new(
        MemoryPropagationStore::new(64 * 1024),
        PropagationNodeConfig {
            stamp_cost: 200,
            stamp_cost_flexibility: 0,
            ..PropagationNodeConfig::default()
        },
    );
    let envelope = hex_bytes("VEC-PN-UPLOAD", "envelope_hex");
    let outcome = node.handle_upload(&envelope, FIXED_TIMESTAMP, |transient_id, stamp| {
        validate(transient_id, stamp, 200)
    });
    match outcome {
        UploadOutcome::InvalidStamp { reject } => assert_eq!(
            reject,
            hex_bytes("VEC-PN-UPLOAD", "invalid_stamp_reject_hex"),
            "the reject packet must be Python's msgpack [ERROR_INVALID_STAMP]"
        ),
        other => panic!("a failing stamp must be rejected: {other:?}"),
    }
    assert!(node.store().is_empty());
}

#[test]
fn the_get_exchange_matches_the_reference_handler_byte_for_byte() {
    let (mut node, small_tid, big_tid) = seeded_node();
    let mailbox = destination();

    // List: both ids, smallest first, byte-identical to the genuine
    // handler's packed return.
    let list = node
        .handle_get(
            &MessageGetRequest::list().encode().unwrap(),
            &mailbox,
            FIXED_TIMESTAMP,
        )
        .unwrap();
    match list {
        GetOutcome::List { response, count } => {
            assert_eq!(count, 2);
            assert_eq!(
                response,
                hex_bytes("VEC-PN-GET-EXCHANGE", "list_response_hex")
            );
        }
        other => panic!("{other:?}"),
    }

    // Fetch under the client's 0.2 kB limit: the small message only,
    // stamp stripped, byte-identical.
    let fetch = MessageGetRequest {
        wants: Some(vec![small_tid, big_tid]),
        haves: Some(Vec::new()),
        transfer_limit_kb: Some(TransferLimit::Float(0.2)),
    };
    let fetched = node
        .handle_get(&fetch.encode().unwrap(), &mailbox, FIXED_TIMESTAMP)
        .unwrap();
    match fetched {
        GetOutcome::Fetch { plan, .. } => {
            assert_eq!(plan.served_ids(), vec![small_tid]);
            let golden = hex_bytes("VEC-PN-GET-EXCHANGE", "fetch_response_hex");
            assert_eq!(node.encode_fetch(&plan).unwrap(), golden);
            assert_eq!(plan.encoded_len(), golden.len());
            // And the STREAMED form, record by record out of the store,
            // is the same bytes (#384 B2). This is the one place in the
            // suite where the part cutter's framing is held against
            // Python's own output rather than against our encoder.
            let mut source = node.fetch_source(&plan);
            let mut streamed = Vec::new();
            let mut buf = [0u8; 7];
            loop {
                let read = source.read(&mut buf).unwrap();
                if read == 0 {
                    break;
                }
                streamed.extend_from_slice(&buf[..read]);
            }
            assert_eq!(
                streamed, golden,
                "the streamed fetch must be the reference's own bytes"
            );
        }
        other => panic!("{other:?}"),
    }

    // The acknowledgement purges the confirmed message and answers the
    // empty list, byte-identical.
    let ack = MessageGetRequest::acknowledge(vec![small_tid]);
    let acked = node
        .handle_get(&ack.encode().unwrap(), &mailbox, FIXED_TIMESTAMP)
        .unwrap();
    match acked {
        GetOutcome::Fetch { plan, purged } => {
            assert_eq!(purged, vec![small_tid]);
            assert_eq!(
                node.encode_fetch(&plan).unwrap(),
                hex_bytes("VEC-PN-GET-EXCHANGE", "ack_response_hex")
            );
        }
        other => panic!("{other:?}"),
    }

    // The store shrank exactly as the reference's did
    // (store_size_after_ack = 1), and the next list matches its bytes.
    assert_eq!(node.store().len(), 1);
    let after = node
        .handle_get(
            &MessageGetRequest::list().encode().unwrap(),
            &mailbox,
            FIXED_TIMESTAMP,
        )
        .unwrap();
    match after {
        GetOutcome::List { response, .. } => assert_eq!(
            response,
            hex_bytes("VEC-PN-GET-EXCHANGE", "list_after_ack_response_hex")
        ),
        other => panic!("{other:?}"),
    }

    // A different mailbox sees the empty list the reference sent the
    // stranger identity (stranger_list_response_hex).
    let stranger = node
        .handle_get(
            &MessageGetRequest::list().encode().unwrap(),
            &[0x55; DESTINATION_LENGTH],
            FIXED_TIMESTAMP,
        )
        .unwrap();
    match stranger {
        GetOutcome::List { response, count } => {
            assert_eq!(count, 0);
            assert_eq!(
                response,
                hex_bytes("VEC-PN-GET-EXCHANGE", "stranger_list_response_hex")
            );
        }
        other => panic!("{other:?}"),
    }
}

#[test]
fn our_announce_matches_the_reference_announce_byte_for_byte() {
    // VEC-ANN-PROPAGATION pins the seven-field app_data for the reference's
    // defaults (256/10240/[16,3,18]/"Node") at the fixed timebase. Our
    // encoder configured identically must produce identical bytes.
    let node = PropagationNode::new(
        MemoryPropagationStore::new(1024),
        PropagationNodeConfig {
            transfer_limit_kb: 256,
            sync_limit_kb: 256 * 40,
            stamp_cost: 16,
            stamp_cost_flexibility: 3,
            peering_cost: 18,
            name: Some(b"Node".to_vec()),
            ..PropagationNodeConfig::default()
        },
    );
    assert_eq!(
        node.announce_app_data(1_700_000_000),
        hex_bytes("VEC-ANN-PROPAGATION", "app_data_hex")
    );
}
